//user constants
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAILED = "USER_SIGNIN_FAILED";

export const UPDATE_EMPLOYEE_REQUEST = "UPDATE_EMPLOYEE_REQUEST";
export const UPDATE_EMPLOYEE_SUCCESS = "UPDATE_EMPLOYEE_SUCCESS";
export const UPDATE_EMPLOYEE_FAILED = "UPDATE_EMPLOYEE_FAILED";

export const CHANGE_SESSIONS_COUNT = "CHANGE_SESSIONS_COUNT";
export const CHANGE_SESSIONS_KEYWORD = "CHANGE_SESSIONS_KEYWORD";
export const CHANGE_SESSIONS_STATE = "CHANGE_SESSIONS_STATE";
export const CHANGE_SESSIONS_SEARCHBY = "CHANGE_SESSIONS_SEARCHBY";

// Admin
export const ADMIN_SIGNIN_REQUEST = "ADMIN_SIGNIN_REQUEST";
export const ADMIN_SIGNIN_SUCCESS = "ADMIN_SIGNIN_SUCCESS";
export const ADMIN_SIGNIN_FAILED = "ADMIN_SIGNIN_FAILED";
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";

// Session
export const CREATE_SESSION_REQUEST = "CREATE_SESSION_REQUEST";
export const CREATE_SESSION_SUCCESS = "CREATE_SESSION_SUCCESS";
export const CREATE_SESSION_FAILED = "CREATE_SESSION_FAILED";

export const CURRENT_SESSION_REQUEST = "CURRENT_SESSION_REQUEST";
export const CURRENT_SESSION_SUCCESS = "CURRENT_SESSION_SUCCESS";
export const CURRENT_SESSION_FAILED = "CURRENT_SESSION_FAILED";

export const ALL_SESSION_REQUEST = "ALL_SESSION_REQUEST";
export const ALL_SESSION_SUCCESS = "ALL_SESSION_SUCCESS";
export const ALL_SESSION_FAILED = "ALL_SESSION_FAILED";

export const UPDATE_SESSION_REQUEST = "UPDATE_SESSION_REQUEST";
export const UPDATE_SESSION_SUCCESS = "UPDATE_SESSION_SUCCESS";
export const UPDATE_SESSION_FAILED = "UPDATE_SESSION_FAILED";

export const VEHICLE_ADD_REQUEST = "VEHICLE_ADD_REQUEST";
export const VEHICLE_ADD_SUCCESS = "VEHICLE_ADD_SUCCESS";
export const VEHICLE_ADD_FAILED = "VEHICLE_ADD_FAILED";

export const VEHICLE_MAKE_REQUEST = "VEHICLE_MAKE_REQUEST";
export const VEHICLE_MAKE_SUCCESS = "VEHICLE_MAKE_SUCCESS";
export const VEHICLE_MAKE_FAILED = "VEHICLE_MAKE_FAILED";
