
//user constants
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAILED = "USER_SIGNIN_FAILED";

// Admin
export const ADMIN_SIGNIN_REQUEST = "ADMIN_SIGNIN_REQUEST";
export const ADMIN_SIGNIN_SUCCESS = "ADMIN_SIGNIN_SUCCESS";
export const ADMIN_SIGNIN_FAILED = "ADMIN_SIGNIN_FAILED";
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";

// Session
export const CREATE_SESSION_REQUEST = "CREATE_SESSION_REQUEST"
export const CREATE_SESSION_SUCCESS = "CREATE_SESSION_SUCCESS"
export const CREATE_SESSION_FAILED = "CREATE_SESSION_FAILED"

export const CURRENT_SESSION_REQUEST = "CURRENT_SESSION_REQUEST"
export const CURRENT_SESSION_SUCCESS = "CURRENT_SESSION_SUCCESS"
export const CURRENT_SESSION_FAILED = "CURRENT_SESSION_FAILED"