export const ALL_ADMIN_REQUEST = "ALL_ADMIN_REQUEST"
export const ALL_ADMIN_SUCCESS = "ALL_ADMIN_SUCCESS"
export const ALL_ADMIN_FAILED = "ALL_ADMIN_FAILED"

export const ALL_EMPLOYEES_REQUEST = "ALL_EMPLOYEES_REQUEST"
export const ALL_EMPLOYEES_SUCCESS = "ALL_EMPLOYEES_SUCCESS"
export const ALL_EMPLOYEES_FAILED = "ALL_EMPLOYEES_FAILED"