export const ALL_ADMIN_REQUEST = "ALL_ADMIN_REQUEST";
export const ALL_ADMIN_SUCCESS = "ALL_ADMIN_SUCCESS";
export const ALL_ADMIN_FAILED = "ALL_ADMIN_FAILED";

export const ADD_ADMIN_REQUEST = "ADD_ADMIN_REQUEST";
export const ADD_ADMIN_SUCCESS = "ADD_ADMIN_SUCCESS";
export const ADD_ADMIN_FAILED = "ADD_ADMIN_FAILED";

export const ALL_EMPLOYEES_REQUEST = "ALL_EMPLOYEES_REQUEST";
export const ALL_EMPLOYEES_SUCCESS = "ALL_EMPLOYEES_SUCCESS";
export const ALL_EMPLOYEES_FAILED = "ALL_EMPLOYEES_FAILED";

export const ADD_EMPLOYEE_REQUEST = "ADD_EMPLOYEE_REQUEST";
export const ADD_EMPLOYEE_SUCCESS = "ADD_EMPLOYEE_SUCCESS";
export const ADD_EMPLOYEE_FAILED = "ADD_EMPLOYEE_FAILED";

export const ALL_SESSIONS_REQUEST = "ALL_SESSIONS_REQUEST";
export const ALL_SESSIONS_SUCCESS = "ALL_SESSIONS_SUCCESS";
export const ALL_SESSIONS_FAILED = "ALL_SESSIONS_FAILED";

export const ALL_CALLERS_REQUEST = "ALL_CALLERS_REQUEST";
export const ALL_CALLERS_SUCCESS = "ALL_CALLERS_SUCCESS";
export const ALL_CALLERS_FAILED = "ALL_CALLERS_FAILED";
