export const GET_CALLER_REQUEST = "GET_CALLER_REQUEST";
export const GET_CALLER_SUCCESS = "GET_CALLER_SUCCESS";
export const GET_CALLER_FAILED = "GET_CALLER_FAILED";

export const ADD_CALLER_REQUEST = "ADD_CALLER_REQUEST";
export const ADD_CALLER_SUCCESS = "ADD_CALLER_SUCCESS";
export const ADD_CALLER_FAILED = "ADD_CALLER_FAILED";

export const UPDATE_CALLER_REQUEST = "UPDATE_CALLER_REQUEST";
export const UPDATE_CALLER_SUCCESS = "UPDATE_CALLER_SUCCESS";
export const UPDATE_CALLER_FAILED = "UPDATE_CALLER_FAILED";
