export const GET_RPARTY_REQUEST = "GET_RPARTY_REQUEST";
export const GET_RPARTY_SUCCESS = "GET_RPARTY_SUCCESS";
export const GET_RPARTY_FAILED = "GET_RPARTY_FAILED";

export const RPARTY_ADD_REQUEST = "RPPARTY_ADD_REQUEST";
export const RPARTY_ADD_SUCCESS = "RPPARTY_ADD_SUCCESS";
export const RPARTY_ADD_FAILED = "RPPARTY_ADD_FAILED";

export const UPDATE_RPARTY_REQUEST = "UPDATE_RPARTY_REQUEST";
export const UPDATE_RPARTY_SUCCESS = "UPDATE_RPARTY_SUCCESS";
export const UPDATE_RPARTY_FAILED = "UPDATE_RPARTY_FAILED";